### ISSUE TITLE
[AppImage] Linux Bundled App error & package installation failing on Linux

### ISSUE THREAD

**Issue by ahmedmukhtar1133** [nullxx/electron-active-window#2]
**Issues:**

1. Couldn't install package on Linux machine getting following error:
```
make: Entering directory '/home/ahmadgoraya/Documents/taskick-electron/node_modules/electron-active-window/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  AR(target) Release/obj.target/../node-addon-api/src/nothing.a
  COPY Release/nothing.a
  CXX(target) Release/obj.target/wm/cppsrc/main.o
  CXX(target) Release/obj.target/wm/cppsrc/linux/windowlinux.o
../cppsrc/linux/windowlinux.cpp:6:10: fatal error: X11/extensions/scrnsaver.h: No such file or directory
    6 | #include <X11/extensions/scrnsaver.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [wm.target.mk:125: Release/obj.target/wm/cppsrc/linux/windowlinux.o] Error 1
make: Leaving directory '/home/ahmadgoraya/Documents/taskick-electron/node_modules/electron-active-window/build'

```

2. Made a build from Mac-OS but getting following error when running the .AppImage file
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.mount_TasKicJJznfd/resources/app.asar.unpacked/node_modules/electron-active-window/build/Release/wm.node: invalid ELF header
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/tmp/.mount_TasKicJJznfd/resources/app.asar/node_modules/electron-active-window/index.js:1:23)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)

```

**Environment:**
- Linux build-essentials and GCC are installed
- OS: Linux
- Electron active window version: 0.06
- Node-Sass: 4.14.1 || 5.0.0 
- Node-gyp: 7.1.2 || 8.0.2

Screenshots are also attached for reference:
![image](https://user-images.githubusercontent.com/15345707/131548172-bd96f177-0eb6-433a-ad16-382bc7e9e4a8.png)

![image](https://user-images.githubusercontent.com/15345707/131548535-eca68156-9838-467a-a398-669e4f1bb876.png)

**Comment by nullxx** [comment]
Could you try installing xorg?

```console
sudo apt install xorg
```

**Comment by Prat1143** [comment]
Facing the exact same problem. Any solution???

**Comment by Prat1143** [comment]
> Do you have `libX11-devel` installed? @Prat1143

Yes, it's already installed to the newest version

**Comment by Prat1143** [comment]
Any update on this issue?

**Comment by nullxx** [comment]
Could it be related to https://groups.google.com/a/chromium.org/g/chromium-dev/c/1XFI04Rd6Mc/m/rLZDp2wnfLoJ ?

**Comment by somerandomcloud** [comment]
The issue you posted doesnt seem to give any answers... Any updates at all?

**Comment by nullxx** [comment]
Sorry but I have no time right now to resolve this problem. I will lock this issue until then
